stages:
  - build
  - test
  - deploy

variables:
  PROJECT_NAME: "DetectionApp"
  DOCKER_IMAGE: ""

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
  only:
    - main
  tags:
    - docker

test:
  stage: test
  script:
    - echo "Running tests..."
  only:
    - main
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - echo "Deploying to Docker registry..."
  only:
    - main
  tags:
    - docker

deploy_to_k8s:
  stage: deploy
  script:
    - echo "Deploying to Kubernetes cluster..."
    - kubectl apply -f k8s-deployment.yaml
  only:
    - main
  environment:
    name: production
    url: http://your-production-url.com
  tags:
    - kubernetes
